### ISSUE TITLE
O programa não para mesmo depois de encontrar a chave

### ISSUE THREAD

**Issue by 21orangehat** [juliano-xd/PyFinder#2]
Olá, ao executar para encontrar qualquer chave dos puzzle (ex 21) mesmo depois de encontrar o programa continua buscando.

E as vezes "reencontra" a mesma chave e continua buscando

![2024-09-26_12-18](https://github.com/user-attachments/assets/53784bfb-c73a-4add-82e3-f0e1a8904b2f)

**Comment by juliano-xd** [comment]
entendi.
eu fiz esse programa apenas como um treino para entender um pouco do processo para a geração de endereços. nao fiz ele tao refinado nem me preocupei com bugs, apenas se ele funcionava haha. mas isso é simples de resolver

**Comment by juliano-xd** [comment]
isso acontece porque cada "worker", opera idependente um do outro. esse codigo é bem injenuo mesmo, ja que foi apenas de experiencia

**Comment by 21orangehat** [comment]
Será que seria possível colocar um worker manager que ficasse responsável por parar todos os workers assim que a chave/target for encontrado?

Infelizmente eu não manjo muito de threads para poder ajudar nesta parte.

**Comment by juliano-xd** [comment]
sim, basta apenas colocar um valor booleano global volatil, tipo:

bool encontrou = false;

e colocar cada thread para procurar enquanto a essa condiçao for  falsa, e caso uma delas encontre a chave, elas mesmas mudem o valor para true, assim, parando todas as outras que estao procurando.

**Comment by juliano-xd** [comment]
se voce se interessar, eu fiz o mesmo programa, mas em kotlin:
https://github.com/juliano-xd/bit_finder.git

**Comment by 21orangehat** [comment]
Eu fiz as alterações sugeridas para resolver o problema mas devo ter feito algo errado, pois o programa, apesar de estar parando, ele diz ter encontrato não apenas o endereço target mas outros endereços que não tem nada a ver com o target.

O que fiz:

a) Adicionei uma constante global
`ENCONTROU: bool = False`

b) No método run, estou especificando para continuar o loop enquanto a variável global estiver False

```
def run(self):
        global ENCONTROU
        publickey = None
        while not publickey == self.target and ENCONTROU == False:
        ....
```

c) Ainda no método run, estou alterando a variável global para False assim que a primeira ocorrência for alcançada.
           ```
with self.lock:
       ...
       ENCONTROU = True
```

**Comment by 21orangehat** [comment]
![2024-09-26_18-15](https://github.com/user-attachments/assets/2a18b749-03b4-49f5-9683-e9cfe63601d1)

**Comment by juliano-xd** [comment]
isso acontece pq todos os workers tem a condicional para quando achar, informar qual foi a chave privada , e como quando um acha a chave de objetivo, ela seta para verdedeiro , todos sao setados para verdadeiro, isso faz com que todos mostrem as chaves privadas em que pararam

**Comment by juliano-xd** [comment]
isso nao chega a ser um problema, ja que o importante é encontrar a target e informar a chave privada dela. é algo para se preocupar apenas se vc quiser deixar a parte "visual", mais clara
